output:
  save_dir: /srv/beegfs/scratch/groups/rodem/flows4flows/
  name: test

general:
  data_dim: 2
  ncond: 1

base_dist:
  data: ConditionalAnulus
  ncond: 1
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 5
  gclip: 5
  nstack: 4
  nblocks: 4
  nnodes: 20
  nbins: 4
  activation: relu
  coupling: True
  coupling_width: 32
  coupling_depth: 2

top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  epochs: 40
  flow4flow: delta
  gclip: 5
  nstack: 4
  nblocks: 4
  nnodes: 20
  nbins: 4
  activation: relu
  coupling: True
  coupling_width: 32
  coupling_depth: 2

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
