output:
  save_dir: /srv/beegfs/scratch/groups/rodem/flows4flows/
  name: test

general:
  data_dim: 2
  n_points: 1e5
  ncond: 0

base_dist:
  left:
    data: ConcentricRings
    load_path: None
    batch_size: 128
    lr: 1e-4
    nepochs: 32
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu
    coupling: False
    coupling_width: 32
    coupling_depth: 2

  right:
    data: Checkerboard
    load_path: None
    batch_size: 128
    lr: 1e-4
    nepochs: 32
    gclip: 5
    nstack: 4
    nblocks: 2
    nnodes: 128
    nbins: 8
    activation: relu
    coupling: False
    coupling_width: 32
    coupling_depth: 2

top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  nepochs: 24
  flow4flow: discretebase
  direction: alternate
  iteration_steps: 5
  gclip: 5
  nstack: 4
  nblocks: 2
  nnodes: 128
  nbins: 8
  activation: leaky_relu
  coupling: False
  coupling_width: 32
  coupling_depth: 2
  penalty: None
  penalty_weight: 1
  anneal: 0

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .