output:
  save_dir: /srv/beegfs/scratch/groups/rodem/flows4flows/
  name: test

base_dist:
  base_dist_l:
    data: Checkerboard
    load_path: None
    batch_size: 128
    lr: 1e-4
    epochs: 40
    gclip: 5
    nstack: 4
    nblocks: 4
    nnodes: 20
    nbins: 4
    activation: leaky_relu
    coupling: True
    coupling_width: 32
    coupling_depth: 2

  base_dist_r:
    data: ConcentricRings
    load_path: None
    batch_size: 128
    lr: 1e-4
    epochs: 40
    gclip: 5
    nstack: 4
    nblocks: 4
    nnodes: 20
    nbins: 4
    activation: leaky_relu
    coupling: True
    coupling_width: 32
    coupling_depth: 2

top_transformer:
  load_path: None
  batch_size: 128
  lr: 1e-4
  epochs: 40
  direction: iterate
  gclip: 5
  nstack: 4
  nblocks: 4
  nnodes: 20
  nbins: 4
  activation: leaky_relu
  coupling: True
  coupling_width: 32
  coupling_depth: 2